In [ ]:
#preprocession
#Impute
#feature_selection
#decomposition

In [1]:
#无量纲化
from sklearn.preprocessing import MinMaxScaler
data = [[-1,2],[-0.5, 6], [0,10],[1,18]]

/root/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/root/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
import pandas as pd
pd.DataFrame(data)

/root/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/root/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [3]:
#归一化
scaler = MinMaxScaler()
scaler.fit(data)
result = scaler.transform(data)
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [4]:
result_ = scaler.fit_transform(data)
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [6]:
scaler.inverse_transform(result)#返回归一化前的数据

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [7]:
scaler = MinMaxScaler(feature_range=[5,10])
scaler.fit_transform(data)

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [8]:
#数据量大使用partial_fit
scaler = scaler.partial_fit(data)

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
scaler.mean_

array([-0.125,  9.   ])

In [12]:
scaler.var_

array([ 0.546875, 35.      ])

In [13]:
scaler.fit_transform(data) #fit接口最小2维

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [14]:
#大多情况下使用标准化，归一化容易受极端值影响

In [28]:
#缺失值
data = [[,1,999],[9,,100],[4,15,],[0,,48],[3,5,]]
data = pd.DataFrame(data)

SyntaxError: invalid syntax (<ipython-input-28-5f60bc7cf8ef>, line 2)

In [22]:
data

0   1    2
0      1  999
1  9      100
2  4  15     
3  0       48
4  3   5

In [25]:
data_0 = data.loc[:,1].values.reshape(-1,1)
data_0

array([[1],
       [''],
       [15],
       [''],
       [5]], dtype=object)

In [26]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer()
imp_median = SimpleImputer(strategy='median')
imp_0 = SimpleImputer(strategy='constant', fill_value=0)

In [1]:
imp_mean = imp_mean.fit_transform(data)

NameError: name 'imp_mean' is not defined